from __future__ import annotations


SCHEMA_VERSION = "2026-04-05"


ANSWER_RESULT_SCHEMA: dict = {
    "type": "object",
    "required": [
        "schema_version",
        "query",
        "scope",
        "question_type",
        "route",
        "status",
        "grounded",
        "answer",
        "evidence",
        "citations",
        "warnings",
        "source_type",
        "doc_id",
        "explain_style",
        "teaching_explanation",
        "response_mode",
        "final_answer_source",
    ],
    "properties": {
        "schema_version": {"type": "string"},
        "query": {"type": "string"},
        "scope": {"type": "string"},
        "question_type": {"type": "string"},
        "route": {"type": "string"},
        "status": {"type": "string"},
        "grounded": {"type": "boolean"},
        "answer": {"type": "string"},
        "evidence": {"type": "array", "items": {"type": "string"}},
        "citations": {"type": "array", "items": {"type": "string"}},
        "warnings": {"type": "array", "items": {"type": "string"}},
        "source_type": {"type": ["string", "null"]},
        "doc_id": {"type": ["string", "null"]},
        "explain_style": {"type": ["string", "null"]},
        "teaching_explanation": {"type": ["object", "null"]},
        "option_reviews": {"type": ["array", "null"]},
        "exam_assessment": {"type": ["object", "null"]},
        "llm_provider": {"type": ["string", "null"]},
        "llm_model": {"type": ["string", "null"]},
        "llm_answer": {"type": ["string", "null"]},
        "llm_error": {"type": ["string", "null"]},
        "response_mode": {"type": ["string", "null"]},
        "final_answer_source": {"type": ["string", "null"]},
        "judge_mode": {"type": ["string", "null"]},
        "judge_result": {"type": ["object", "null"]},
        "judge_error": {"type": ["string", "null"]},
        "judge_trace": {"type": ["array", "null"]},
        "judge_runs": {"type": ["object", "null"]},
        "agent_prompts": {"type": ["object", "null"]},
        "agent_runs": {"type": ["object", "null"]},
        "fallback_trace": {"type": ["array", "null"]},
    },
}
